export const PL =[
  {id:"bardo",n:"Musée du Bardo",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.81,lg:10.14,rt:4.7,dur:120,cost:13,hid:false,sn:["printemps","ete","automne","hiver"],cr:.6,d:"Plus grande collection mosaïques romaines au monde.",meal:null},
  {id:"medina_t",n:"Médina de Tunis",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.17,rt:4.5,dur:100,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.88,d:"UNESCO. 700+ monuments, mosquée Zitouna.",meal:null},
  {id:"marche",n:"Marché Central",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.18,rt:4.2,dur:50,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.78,d:"Poissons, épices, olives, harissa artisanale.",meal:null},
  {id:"fondouk",n:"Fondouk El Attarine",r:"tunis",sub:"Tunis Centre",cat:"cafe",lt:36.80,lg:10.17,rt:4.4,dur:40,cost:12,hid:true,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Thé à la menthe dans fondouk du XVIIe.",meal:"breakfast"},
  {id:"cafe_mr",n:"Café M'Rabet",r:"tunis",sub:"Tunis Centre",cat:"cafe",lt:36.80,lg:10.17,rt:4.3,dur:35,cost:8,hid:true,sn:["printemps","ete","automne","hiver"],cr:.40,d:"Plus vieux café de Tunis, ftour traditionnel.",meal:"breakfast"},
  {id:"dar_med",n:"Dar El Medina",r:"tunis",sub:"Tunis Centre",cat:"restaurant",lt:36.80,lg:10.17,rt:4.6,dur:75,cost:45,hid:true,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Gastronomie raffinée dans palais XVIIIe.",meal:"dinner"},
  {id:"belhadj",n:"Dar Bel Hadj",r:"tunis",sub:"Tunis Centre",cat:"restaurant",lt:36.80,lg:10.17,rt:4.5,dur:70,cost:35,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Couscous au mérou, cadre somptueux.",meal:"lunch"},
  {id:"belved",n:"Parc du Belvédère",r:"tunis",sub:"Tunis Centre",cat:"nature",lt:36.82,lg:10.16,rt:4.0,dur:50,cost:0,hid:true,sn:["printemps","ete","automne"],cr:.35,d:"110 ha de verdure, zoo, koubba.",meal:null},
  {id:"carthage",n:"Site de Carthage",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.85,lg:10.32,rt:4.6,dur:100,cost:12,hid:false,sn:["printemps","automne","hiver"],cr:.82,d:"UNESCO. Thermes d'Antonin, Byrsa.",meal:null},
  {id:"sbs",n:"Sidi Bou Saïd",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.87,lg:10.35,rt:4.8,dur:80,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.85,d:"Village bleu et blanc mythique.",meal:null},
  {id:"nattes",n:"Café des Nattes",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"cafe",lt:36.87,lg:10.35,rt:4.5,dur:40,cost:8,hid:false,sn:["printemps","ete","automne"],cr:.80,d:"Café historique 1700. Thé aux pignons.",meal:"breakfast"},
  {id:"zarrouk",n:"Dar Zarrouk",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"restaurant",lt:36.87,lg:10.35,rt:4.7,dur:80,cost:65,hid:false,sn:["printemps","ete","automne"],cr:.40,d:"Table gastronomique vue panoramique mer.",meal:"dinner"},
  {id:"bonvieux",n:"Au Bon Vieux Temps",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"restaurant",lt:36.87,lg:10.35,rt:4.4,dur:70,cost:40,hid:false,sn:["printemps","ete","automne"],cr:.55,d:"Terrasse vue mer, méditerranéenne.",meal:"lunch"},
  {id:"marsa_pl",n:"Plage La Marsa",r:"tunis",sub:"La Marsa & Gammarth",cat:"beach",lt:36.88,lg:10.33,rt:4.3,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.65,d:"Banlieue balnéaire chic, galeries.",meal:null},
  {id:"boga",n:"Boga Beach Club",r:"tunis",sub:"La Marsa & Gammarth",cat:"beach",lt:36.89,lg:10.31,rt:4.2,dur:120,cost:30,hid:false,sn:["ete"],cr:.70,d:"Beach club, DJ sets, piscine.",meal:null},
  {id:"s_med",n:"Médina Sousse",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.83,lg:10.64,rt:4.4,dur:80,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.65,d:"UNESCO. Ribat VIIIe, Grande Mosquée.",meal:null},
  {id:"kantaoui",n:"Port El Kantaoui",r:"sahel",sub:"Sousse",cat:"beach",lt:35.89,lg:10.59,rt:4.1,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.70,d:"Marina luxe, golf, parc aquatique.",meal:null},
  {id:"golfe_r",n:"Le Golfe",r:"sahel",sub:"Sousse",cat:"restaurant",lt:35.83,lg:10.64,rt:4.3,dur:70,cost:30,hid:false,sn:["printemps","ete","automne","hiver"],cr:.50,d:"Fruits de mer face au vieux port.",meal:"lunch"},
  {id:"cafe_s",n:"Café de la Place",r:"sahel",sub:"Sousse",cat:"cafe",lt:35.83,lg:10.64,rt:4.1,dur:35,cost:8,hid:false,sn:["printemps","ete","automne","hiver"],cr:.60,d:"Petit-déjeuner tunisien face médina.",meal:"breakfast"},
  {id:"takr",n:"Village Takrouna",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.85,lg:10.59,rt:4.5,dur:60,cost:0,hid:true,sn:["printemps","automne"],cr:.08,d:"Village berbère perché spectaculaire.",meal:null},
  {id:"m_rib",n:"Ribat Monastir",r:"sahel",sub:"Monastir",cat:"attraction",lt:35.78,lg:10.83,rt:4.3,dur:50,cost:8,hid:false,sn:["printemps","ete","automne","hiver"],cr:.50,d:"Forteresse VIIIe, lieu de tournage.",meal:null},
  {id:"bourg_m",n:"Mausolée Bourguiba",r:"sahel",sub:"Monastir",cat:"attraction",lt:35.78,lg:10.83,rt:4.2,dur:30,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.40,d:"Monument doré imposant.",meal:null},
  {id:"marina_m",n:"Marina Monastir",r:"sahel",sub:"Monastir",cat:"cafe",lt:35.78,lg:10.84,rt:4.0,dur:40,cost:12,hid:false,sn:["printemps","ete","automne"],cr:.45,d:"Brunch face aux yachts.",meal:"breakfast"},
  {id:"neptune",n:"Le Neptune",r:"sahel",sub:"Mahdia",cat:"restaurant",lt:35.51,lg:11.05,rt:4.3,dur:70,cost:25,hid:true,sn:["printemps","ete","automne"],cr:.20,d:"Poisson grillé au port de Mahdia.",meal:"dinner"},
  {id:"eljem",n:"Amphithéâtre El Jem",r:"centre",sub:"El Jem",cat:"attraction",lt:35.30,lg:10.71,rt:4.9,dur:80,cost:12,hid:false,sn:["printemps","automne","hiver"],cr:.55,d:"3ème colisée romain. UNESCO.",meal:null},
  {id:"tabarka",n:"Tabarka",r:"nord_ouest",sub:"Tabarka",cat:"nature",lt:36.95,lg:8.76,rt:4.4,dur:120,cost:0,hid:false,sn:["ete","printemps"],cr:.32,d:"Côte de corail, Les Aiguilles.",meal:null},
  {id:"fort_g",n:"Fort Génois",r:"nord_ouest",sub:"Tabarka",cat:"attraction",lt:36.96,lg:8.75,rt:4.2,dur:40,cost:0,hid:true,sn:["printemps","ete","automne"],cr:.20,d:"Forteresse génoise sur île rocheuse.",meal:null},
  {id:"resto_tab",n:"Chez Nous",r:"nord_ouest",sub:"Tabarka",cat:"restaurant",lt:36.95,lg:8.76,rt:4.2,dur:65,cost:28,hid:false,sn:["printemps","ete","automne"],cr:.25,d:"Langoustes du corail.",meal:"lunch"},
  {id:"ain_d",n:"Aïn Draham",r:"nord_ouest",sub:"Aïn Draham",cat:"nature",lt:36.78,lg:8.68,rt:4.3,dur:90,cost:0,hid:true,sn:["ete","printemps","automne"],cr:.15,d:"Village montagne 800m, forêts de chênes.",meal:null},
  {id:"cafe_f",n:"Café de la Forêt",r:"nord_ouest",sub:"Aïn Draham",cat:"cafe",lt:36.79,lg:8.68,rt:4.1,dur:35,cost:8,hid:true,sn:["ete","printemps","automne"],cr:.10,d:"Thé sous les chênes-lièges centenaires.",meal:"breakfast"},
  {id:"bulla",n:"Bulla Regia",r:"nord_ouest",sub:"Bulla Regia",cat:"attraction",lt:36.56,lg:8.76,rt:4.5,dur:80,cost:7,hid:true,sn:["printemps","ete","automne"],cr:.12,d:"Villas romaines souterraines uniques.",meal:null},
  {id:"bizerte",n:"Vieux Port Bizerte",r:"nord_est",sub:"Bizerte",cat:"attraction",lt:37.27,lg:9.87,rt:4.2,dur:70,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.35,d:"Port pittoresque, Kasbah colorée.",meal:null},
  {id:"mousse",n:"Le Petit Mousse",r:"nord_est",sub:"Bizerte",cat:"restaurant",lt:37.28,lg:9.88,rt:4.3,dur:65,cost:25,hid:false,sn:["printemps","ete","automne"],cr:.30,d:"Poissons grillés face au port.",meal:"lunch"},
  {id:"ichkeul",n:"Parc Ichkeul",r:"nord_est",sub:"Ichkeul",cat:"nature",lt:37.16,lg:9.67,rt:4.6,dur:100,cost:5,hid:true,sn:["hiver","automne","printemps"],cr:.10,d:"UNESCO. Flamants roses, lac unique.",meal:null},
  {id:"cafe_biz",n:"Café du Port",r:"nord_est",sub:"Bizerte",cat:"cafe",lt:37.27,lg:9.87,rt:4.0,dur:35,cost:7,hid:false,sn:["printemps","ete","automne"],cr:.30,d:"Bambalouni et café au lait matinal.",meal:"breakfast"},
  {id:"dougga",n:"Dougga",r:"nord_ouest",sub:"Testour & Dougga",cat:"attraction",lt:36.42,lg:9.22,rt:4.8,dur:100,cost:8,hid:false,sn:["printemps","automne"],cr:.22,d:"Meilleur site romain d'Afrique. UNESCO.",meal:null},
  {id:"testour",n:"Testour",r:"nord_ouest",sub:"Testour & Dougga",cat:"attraction",lt:36.55,lg:9.45,rt:4.1,dur:50,cost:0,hid:true,sn:["printemps","automne"],cr:.08,d:"Village andalou, horloge inversée.",meal:null},
  {id:"jugurtha",n:"Table de Jugurtha",r:"nord_ouest",sub:"Le Kef",cat:"nature",lt:35.79,lg:8.39,rt:4.7,dur:100,cost:5,hid:true,sn:["printemps","automne"],cr:.05,d:"Mesa 1271m, randonnée mythique.",meal:null},
  {id:"h_med",n:"Médina Hammamet",r:"cap_bon",sub:"Hammamet",cat:"attraction",lt:36.39,lg:10.61,rt:4.3,dur:50,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.65,d:"Médina fortifiée face mer, jasmin.",meal:null},
  {id:"h_pl",n:"Plage Hammamet",r:"cap_bon",sub:"Hammamet",cat:"beach",lt:36.40,lg:10.62,rt:4.4,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.60,d:"Sable fin, eaux turquoise.",meal:null},
  {id:"bella",n:"La Bella Marina",r:"cap_bon",sub:"Hammamet",cat:"restaurant",lt:36.40,lg:10.61,rt:4.4,dur:70,cost:35,hid:false,sn:["printemps","ete","automne"],cr:.50,d:"Tuniso-italienne, terrasse mer.",meal:"dinner"},
  {id:"nabeul",n:"Nabeul Poteries",r:"cap_bon",sub:"Nabeul",cat:"attraction",lt:36.45,lg:10.74,rt:4.1,dur:70,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.45,d:"Capitale de la poterie tunisienne.",meal:null},
  {id:"cafe_hamm",n:"Café Sidi Bouhdid",r:"cap_bon",sub:"Hammamet",cat:"cafe",lt:36.39,lg:10.61,rt:4.3,dur:35,cost:10,hid:false,sn:["printemps","ete","automne"],cr:.55,d:"Bambalouni vue mer, petit-déj.",meal:"breakfast"},
  {id:"k_mosq",n:"Grande Mosquée",r:"centre",sub:"Kairouan",cat:"mosque",lt:35.68,lg:10.10,rt:4.8,dur:50,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.60,d:"4ème lieu saint Islam. Fondée 670.",meal:null},
  {id:"k_med",n:"Médina Kairouan",r:"centre",sub:"Kairouan",cat:"attraction",lt:35.68,lg:10.10,rt:4.4,dur:70,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.50,d:"UNESCO. Tapis, makroudh artisanal.",meal:null},
  {id:"aghlab",n:"Bassins Aghlabides",r:"centre",sub:"Kairouan",cat:"attraction",lt:35.69,lg:10.11,rt:4.3,dur:40,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.35,d:"Prouesse hydraulique IXe siècle.",meal:null},
  {id:"bouzid",n:"Pâtisserie Bouzid",r:"centre",sub:"Kairouan",cat:"cafe",lt:35.68,lg:10.10,rt:4.5,dur:30,cost:5,hid:false,sn:["printemps","ete","automne","hiver"],cr:.50,d:"Meilleurs makroudh de Kairouan.",meal:"breakfast"},
  {id:"tozeur",n:"Palmeraie Tozeur",r:"sud_ouest",sub:"Tozeur",cat:"nature",lt:33.92,lg:8.13,rt:4.6,dur:90,cost:5,hid:false,sn:["automne","hiver","printemps"],cr:.38,d:"400 000 palmiers millénaires.",meal:null},
  {id:"tozeur_v",n:"Ouled El Hadef",r:"sud_ouest",sub:"Tozeur",cat:"attraction",lt:33.92,lg:8.13,rt:4.3,dur:50,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.30,d:"Briques jaunes géométriques.",meal:null},
  {id:"chott",n:"Chott el-Jérid",r:"sud_ouest",sub:"Tozeur",cat:"nature",lt:33.75,lg:8.42,rt:4.5,dur:50,cost:0,hid:false,sn:["automne","hiver","printemps"],cr:.15,d:"Lac salé 5000km2. Mirages.",meal:null},
  {id:"dar_toz",n:"Dar Tozeur",r:"sud_ouest",sub:"Tozeur",cat:"restaurant",lt:33.92,lg:8.13,rt:4.4,dur:70,cost:25,hid:false,sn:["automne","hiver","printemps"],cr:.25,d:"Couscous berzguen, spécialité locale.",meal:"dinner"},
  {id:"chebika",n:"Oasis Chebika",r:"sud_ouest",sub:"Nefta & Chebika",cat:"nature",lt:34.32,lg:7.94,rt:4.7,dur:80,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.20,d:"Cascade cachée dans les gorges.",meal:null},
  {id:"mides",n:"Canyon Mides",r:"sud_ouest",sub:"Tamerza",cat:"nature",lt:34.38,lg:7.90,rt:4.5,dur:60,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.10,d:"Gorges vertigineuses.",meal:null},
  {id:"ong",n:"Ong Jmal Star Wars",r:"sud_ouest",sub:"Nefta & Chebika",cat:"attraction",lt:34.40,lg:7.85,rt:4.2,dur:50,cost:5,hid:true,sn:["automne","hiver","printemps"],cr:.12,d:"Décors Mos Espa dans le sable.",meal:null},
  {id:"matmata",n:"Matmata Troglodytes",r:"sud_est",sub:"Matmata",cat:"attraction",lt:33.54,lg:9.98,rt:4.4,dur:70,cost:5,hid:false,sn:["automne","hiver","printemps"],cr:.30,d:"Habitations berbères Star Wars.",meal:null},
  {id:"douz",n:"Douz Sahara",r:"sud_ouest",sub:"Douz",cat:"nature",lt:33.46,lg:8.83,rt:4.3,dur:120,cost:35,hid:false,sn:["automne","hiver"],cr:.28,d:"Porte du Sahara. Dromadaires, dunes.",meal:null},
  {id:"ksar_o",n:"Ksour Tataouine",r:"sud_est",sub:"Tataouine",cat:"attraction",lt:32.93,lg:10.45,rt:4.4,dur:80,cost:5,hid:true,sn:["automne","hiver","printemps"],cr:.08,d:"Greniers berbères millénaires.",meal:null},
  {id:"chenini",n:"Village Chenini",r:"sud_est",sub:"Tataouine",cat:"attraction",lt:33.01,lg:10.26,rt:4.5,dur:70,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.05,d:"Troglodyte perché légendaire.",meal:null},
  {id:"houmt",n:"Houmt Souk",r:"djerba",sub:"Houmt Souk",cat:"attraction",lt:33.88,lg:10.86,rt:4.3,dur:90,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.55,d:"Fondouks, marchés berbères.",meal:null},
  {id:"yedder",n:"Café Ben Yedder",r:"djerba",sub:"Houmt Souk",cat:"cafe",lt:33.88,lg:10.86,rt:4.2,dur:40,cost:8,hid:false,sn:["printemps","ete","automne","hiver"],cr:.40,d:"Ftour, thé vert, pâtisseries.",meal:"breakfast"},
  {id:"atik",n:"Al Atik",r:"djerba",sub:"Houmt Souk",cat:"restaurant",lt:33.88,lg:10.86,rt:4.4,dur:70,cost:30,hid:false,sn:["printemps","ete","automne","hiver"],cr:.45,d:"Cuisine djerbienne, poisson du jour.",meal:"lunch"},
  {id:"ghriba",n:"Synagogue Ghriba",r:"djerba",sub:"Erriadh",cat:"attraction",lt:33.81,lg:10.86,rt:4.5,dur:40,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.40,d:"Plus ancienne synagogue d'Afrique.",meal:null},
  {id:"djhood",n:"Djerbahood",r:"djerba",sub:"Erriadh",cat:"attraction",lt:33.82,lg:10.86,rt:4.6,dur:70,cost:0,hid:true,sn:["printemps","ete","automne","hiver"],cr:.30,d:"250 fresques street art, 30 pays.",meal:null},
  {id:"seguia",n:"Plage Seguia",r:"djerba",sub:"Midoun",cat:"beach",lt:33.80,lg:10.96,rt:4.4,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.45,d:"Paradis turquoise.",meal:null},
  {id:"dar_dj",n:"Dar Hassine",r:"djerba",sub:"Midoun",cat:"restaurant",lt:33.80,lg:10.92,rt:4.5,dur:75,cost:35,hid:true,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Table raffinée djerbienne.",meal:"dinner"},
  {id:"sfax_m",n:"Médina Sfax",r:"sfax",sub:"Sfax Ville",cat:"attraction",lt:34.74,lg:10.76,rt:4.2,dur:70,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.40,d:"Remparts majestueux, Bab Diwan.",meal:null},
  {id:"kerk",n:"Îles Kerkennah",r:"sfax",sub:"Kerkennah",cat:"nature",lt:34.70,lg:11.17,rt:4.3,dur:150,cost:3,hid:true,sn:["printemps","ete","automne"],cr:.08,d:"Archipel préservé, pêche.",meal:null},
  // === EXPANDED DESTINATIONS ===
  // TUNIS +
  {id:"cathedrale",n:"Cathédrale St-Vincent",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.18,rt:4.0,dur:30,cost:0,hid:true,sn:["printemps","ete","automne","hiver"],cr:.20,d:"Architecture néo-romane, vitraux magnifiques.",meal:null},
  {id:"dar_lasram",n:"Dar Lasram",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.17,rt:4.3,dur:40,cost:5,hid:true,sn:["printemps","ete","automne","hiver"],cr:.15,d:"Palais beylical XVIIIe, zellige exquis.",meal:null},
  {id:"dar_hussein",n:"Dar Hussein",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.17,rt:4.4,dur:45,cost:5,hid:true,sn:["printemps","ete","automne","hiver"],cr:.18,d:"INP, architecture ottomane splendide.",meal:null},
  {id:"zitouna",n:"Mosquée Zitouna",r:"tunis",sub:"Tunis Centre",cat:"mosque",lt:36.80,lg:10.17,rt:4.6,dur:25,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.70,d:"Fondée en 732, cœur spirituel de Tunis.",meal:null},
  {id:"musee_cart",n:"Musée Carthage",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.85,lg:10.32,rt:4.3,dur:50,cost:8,hid:false,sn:["printemps","automne","hiver"],cr:.50,d:"Stèles puniques, sarcophages, bijoux anciens.",meal:null},
  {id:"thermes",n:"Thermes d'Antonin",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.86,lg:10.33,rt:4.5,dur:50,cost:12,hid:false,sn:["printemps","automne","hiver"],cr:.60,d:"Plus grands thermes romains d'Afrique.",meal:null},
  {id:"acropolium",n:"Acropolium Carthage",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.85,lg:10.33,rt:4.2,dur:35,cost:5,hid:true,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Ancienne cathédrale, concerts, expo.",meal:null},
  {id:"gammarth_pl",n:"Plage Gammarth",r:"tunis",sub:"La Marsa & Gammarth",cat:"beach",lt:36.91,lg:10.30,rt:4.1,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.55,d:"Plage résidentielle chic, sable fin.",meal:null},
  {id:"dar_seb",n:"Dar Sebastian",r:"tunis",sub:"La Marsa & Gammarth",cat:"attraction",lt:36.89,lg:10.32,rt:4.0,dur:40,cost:5,hid:true,sn:["printemps","ete","automne"],cr:.08,d:"Villa art-déco, jardin romantique.",meal:null},
  {id:"cafe_saf",n:"Café Saf Saf",r:"tunis",sub:"La Marsa & Gammarth",cat:"cafe",lt:36.88,lg:10.33,rt:4.3,dur:40,cost:10,hid:false,sn:["printemps","ete","automne","hiver"],cr:.45,d:"Café centenaire sous grand ficus, narguilé.",meal:"breakfast"},
  // SAHEL +
  {id:"ribat_s",n:"Ribat Sousse",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.83,lg:10.64,rt:4.4,dur:45,cost:8,hid:false,sn:["printemps","ete","automne","hiver"],cr:.55,d:"Tour de guet VIIIe, vue panoramique.",meal:null},
  {id:"catacombes",n:"Catacombes Sousse",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.82,lg:10.64,rt:4.1,dur:40,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.15,d:"Réseau souterrain chrétien, 5km galeries.",meal:null},
  {id:"boujaafar",n:"Plage Boujaâfar",r:"sahel",sub:"Sousse",cat:"beach",lt:35.83,lg:10.65,rt:4.0,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.65,d:"Plage urbaine animée face au Ribat.",meal:null},
  {id:"musee_s",n:"Musée Archéo Sousse",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.83,lg:10.63,rt:4.2,dur:50,cost:7,hid:true,sn:["printemps","automne","hiver"],cr:.20,d:"Mosaïques romaines exceptionnelles.",meal:null},
  {id:"habib_r",n:"Restaurant Habib",r:"sahel",sub:"Sousse",cat:"restaurant",lt:35.83,lg:10.64,rt:4.2,dur:65,cost:20,hid:false,sn:["printemps","ete","automne","hiver"],cr:.40,d:"Tajine poisson, spécialités sahéliennes.",meal:"lunch"},
  {id:"dar_am",n:"Dar Amira",r:"sahel",sub:"Sousse",cat:"restaurant",lt:35.83,lg:10.63,rt:4.5,dur:70,cost:35,hid:true,sn:["printemps","ete","automne","hiver"],cr:.20,d:"Palais restauré, gastronomie fine.",meal:"dinner"},
  {id:"skanes_pl",n:"Plage Skanes",r:"sahel",sub:"Monastir",cat:"beach",lt:35.77,lg:10.75,rt:4.2,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.50,d:"Longue plage de sable fin, eaux calmes.",meal:null},
  {id:"habib_mus",n:"Musée Habib Bourguiba",r:"sahel",sub:"Monastir",cat:"attraction",lt:35.78,lg:10.83,rt:4.0,dur:40,cost:5,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Vie du père de la nation.",meal:null},
  {id:"mahdia_med",n:"Médina Mahdia",r:"sahel",sub:"Mahdia",cat:"attraction",lt:35.50,lg:11.04,rt:4.3,dur:70,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.30,d:"Skifa Kahla, tisserands soie.",meal:null},
  {id:"mahdia_pl",n:"Plage Mahdia",r:"sahel",sub:"Mahdia",cat:"beach",lt:35.50,lg:11.06,rt:4.5,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.35,d:"Sable blanc fin, mer transparente.",meal:null},
  {id:"borj_m",n:"Borj El Kebir",r:"sahel",sub:"Mahdia",cat:"attraction",lt:35.51,lg:11.06,rt:4.1,dur:35,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.15,d:"Fort fatimide XVI, vue cap Afrique.",meal:null},
  {id:"port_mahdia",n:"Port de Mahdia",r:"sahel",sub:"Mahdia",cat:"attraction",lt:35.50,lg:11.05,rt:4.2,dur:30,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Port coloré, barques bleues, pêcheurs.",meal:null},
  // NORD-OUEST +
  {id:"corail",n:"Côte de Corail",r:"nord_ouest",sub:"Tabarka",cat:"nature",lt:36.95,lg:8.78,rt:4.5,dur:80,cost:0,hid:false,sn:["ete","printemps"],cr:.20,d:"Fonds marins, plongée, roches rouges.",meal:null},
  {id:"pl_tabarka",n:"Plage Tabarka",r:"nord_ouest",sub:"Tabarka",cat:"beach",lt:36.96,lg:8.74,rt:4.3,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.25,d:"Sable fin, Aiguilles rocheuses en fond.",meal:null},
  {id:"foret_bou",n:"Forêt Boukornine",r:"nord_ouest",sub:"Aïn Draham",cat:"nature",lt:36.78,lg:8.70,rt:4.2,dur:70,cost:0,hid:true,sn:["printemps","ete","automne"],cr:.05,d:"Randonnée en forêt de chênes-lièges.",meal:null},
  {id:"hammam_b",n:"Hammam Bourguiba",r:"nord_ouest",sub:"Aïn Draham",cat:"nature",lt:36.80,lg:8.73,rt:4.0,dur:60,cost:10,hid:true,sn:["printemps","automne","hiver"],cr:.08,d:"Sources thermales naturelles en forêt.",meal:null},
  {id:"chimtou",n:"Chimtou",r:"nord_ouest",sub:"Bulla Regia",cat:"attraction",lt:36.49,lg:8.58,rt:4.1,dur:60,cost:5,hid:true,sn:["printemps","automne"],cr:.05,d:"Carrières marbre numide, musée.",meal:null},
  // NORD-EST +
  {id:"fort_biz",n:"Fort d'Espagne",r:"nord_est",sub:"Bizerte",cat:"attraction",lt:37.28,lg:9.87,rt:4.1,dur:40,cost:3,hid:false,sn:["printemps","ete","automne"],cr:.25,d:"Fort ottoman, vue panoramique port.",meal:null},
  {id:"kasbah_biz",n:"Kasbah Bizerte",r:"nord_est",sub:"Bizerte",cat:"attraction",lt:37.27,lg:9.87,rt:4.0,dur:35,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Quartier historique, ruelles colorées.",meal:null},
  {id:"cafe_biz2",n:"Café du Port",r:"nord_est",sub:"Bizerte",cat:"cafe",lt:37.27,lg:9.87,rt:4.1,dur:35,cost:8,hid:false,sn:["printemps","ete","automne"],cr:.30,d:"Vue vieux port, café turc.",meal:"breakfast"},
  {id:"resto_biz",n:"Le Phénicien",r:"nord_est",sub:"Bizerte",cat:"restaurant",lt:37.28,lg:9.88,rt:4.3,dur:70,cost:30,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Fruits de mer, terrasse sur le port.",meal:"dinner"},
  {id:"corniche_biz",n:"Corniche Bizerte",r:"nord_est",sub:"Bizerte",cat:"nature",lt:37.28,lg:9.85,rt:4.0,dur:50,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.30,d:"Promenade littorale, coucher soleil.",meal:null},
  // CENTRE +
  {id:"kef",n:"Kasbah Le Kef",r:"nord_ouest",sub:"Le Kef",cat:"attraction",lt:36.18,lg:8.71,rt:4.3,dur:60,cost:3,hid:true,sn:["printemps","automne"],cr:.08,d:"Citadelle ottomane, vue 360° vallée.",meal:null},
  {id:"basilique",n:"Basilique Le Kef",r:"nord_ouest",sub:"Le Kef",cat:"attraction",lt:36.17,lg:8.71,rt:4.0,dur:30,cost:0,hid:true,sn:["printemps","automne","hiver"],cr:.05,d:"Paléochrétienne IVe, une des plus anciennes.",meal:null},
  {id:"table_jug",n:"Table de Jugurtha",r:"nord_ouest",sub:"Le Kef",cat:"nature",lt:36.14,lg:8.37,rt:4.6,dur:90,cost:5,hid:true,sn:["printemps","automne"],cr:.03,d:"Mesa spectaculaire, forteresse naturelle.",meal:null},
  {id:"cafe_kef",n:"Café Andalous Le Kef",r:"nord_ouest",sub:"Le Kef",cat:"cafe",lt:36.17,lg:8.71,rt:4.0,dur:30,cost:6,hid:true,sn:["printemps","ete","automne","hiver"],cr:.05,d:"Plus vieux café du Kef, vue médina.",meal:"breakfast"},
  // CAP BON +
  {id:"fort_kel",n:"Fort Kélibia",r:"cap_bon",sub:"Kélibia",cat:"attraction",lt:36.85,lg:11.10,rt:4.3,dur:50,cost:5,hid:false,sn:["printemps","ete","automne"],cr:.30,d:"Plus grand fort byzantin, vue 360°.",meal:null},
  {id:"korbous",n:"Korbous Thermes",r:"cap_bon",sub:"Korbus",cat:"nature",lt:36.82,lg:10.57,rt:4.1,dur:70,cost:10,hid:true,sn:["printemps","automne","hiver"],cr:.10,d:"Sources thermales chaudes, falaises.",meal:null},
  {id:"haouaria",n:"Grottes El Haouaria",r:"cap_bon",sub:"El Haouaria",cat:"nature",lt:37.05,lg:11.01,rt:4.2,dur:50,cost:3,hid:true,sn:["printemps","ete","automne"],cr:.10,d:"Carrières romaines, fauconnerie.",meal:null},
  {id:"yasmine_h",n:"Yasmine Hammamet",r:"cap_bon",sub:"Hammamet",cat:"attraction",lt:36.38,lg:10.55,rt:4.0,dur:80,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.60,d:"Marina, restos, souk reconstitué.",meal:null},
  {id:"cafe_kel",n:"Café El Mansourah",r:"cap_bon",sub:"Kélibia",cat:"cafe",lt:36.84,lg:11.09,rt:4.2,dur:35,cost:8,hid:false,sn:["printemps","ete","automne"],cr:.15,d:"Vue falaises, thé au soleil.",meal:"breakfast"},
  {id:"dar_kel",n:"Le Pêcheur Kélibia",r:"cap_bon",sub:"Kélibia",cat:"restaurant",lt:36.85,lg:11.10,rt:4.4,dur:70,cost:30,hid:false,sn:["printemps","ete","automne"],cr:.20,d:"Poisson fraîchement pêché, terrasse mer.",meal:"dinner"},
  // KAIROUAN +
  {id:"k_med_souk",n:"Souk Médina Kairouan",r:"centre",sub:"Kairouan",cat:"attraction",lt:35.68,lg:10.10,rt:4.2,dur:60,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.45,d:"Tapis, cuir, makroudh artisanaux.",meal:null},
  {id:"sidi_sahbi",n:"Mosquée Sidi Sahbi",r:"centre",sub:"Kairouan",cat:"mosque",lt:35.67,lg:10.09,rt:4.4,dur:30,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Mosquée du Barbier, faïences turques.",meal:null},
  {id:"bir_b",n:"Bassins Aghlabides",r:"centre",sub:"Kairouan",cat:"attraction",lt:35.68,lg:10.11,rt:4.1,dur:25,cost:3,hid:false,sn:["printemps","automne","hiver"],cr:.25,d:"Génie hydraulique IXe siècle.",meal:null},
  {id:"cafe_kairouan",n:"Café El Amir",r:"centre",sub:"Kairouan",cat:"cafe",lt:35.68,lg:10.10,rt:4.0,dur:30,cost:6,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Makroudh frais, thé devant médina.",meal:"breakfast"},
  {id:"resto_kairouan",n:"El Barrouta",r:"centre",sub:"Kairouan",cat:"restaurant",lt:35.68,lg:10.10,rt:4.2,dur:65,cost:22,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Couscous bel kaddid, agneau local.",meal:"lunch"},
  // SUD-OUEST +
  {id:"nefta",n:"Corbeille Nefta",r:"sud_ouest",sub:"Nefta & Chebika",cat:"nature",lt:33.87,lg:7.88,rt:4.3,dur:50,cost:0,hid:false,sn:["automne","hiver","printemps"],cr:.12,d:"Oasis en cuvette, 152 sources.",meal:null},
  {id:"tamerza_pal",n:"Cascades Tamerza",r:"sud_ouest",sub:"Tamerza",cat:"nature",lt:34.38,lg:7.95,rt:4.4,dur:60,cost:0,hid:false,sn:["automne","hiver","printemps"],cr:.12,d:"Oasis de montagne, cascades cachées.",meal:null},
  {id:"tozeur_zoo",n:"Eden Palm Tozeur",r:"sud_ouest",sub:"Tozeur",cat:"nature",lt:33.93,lg:8.10,rt:4.0,dur:50,cost:8,hid:false,sn:["automne","hiver","printemps"],cr:.15,d:"Parc éco, faune saharienne.",meal:null},
  {id:"cafe_toz",n:"Café Bir Barrouta",r:"sud_ouest",sub:"Tozeur",cat:"cafe",lt:33.92,lg:8.13,rt:4.1,dur:30,cost:5,hid:false,sn:["automne","hiver","printemps"],cr:.15,d:"Puits ancestral, dromadaire actionne la pompe.",meal:"breakfast"},
  // SUD-EST +
  {id:"guerm",n:"Guermessa",r:"sud_est",sub:"Tataouine",cat:"attraction",lt:32.99,lg:10.37,rt:4.3,dur:60,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.03,d:"Village perché abandonné, vue saisissante.",meal:null},
  {id:"ksar_h",n:"Ksar Haddada",r:"sud_est",sub:"Tataouine",cat:"attraction",lt:33.16,lg:10.34,rt:4.2,dur:45,cost:3,hid:true,sn:["automne","hiver","printemps"],cr:.05,d:"Lieu de tournage Star Wars, hôtel insolite.",meal:null},
  {id:"cafe_douz",n:"Café des Dunes",r:"sud_ouest",sub:"Douz",cat:"cafe",lt:33.46,lg:8.83,rt:4.0,dur:35,cost:6,hid:false,sn:["automne","hiver"],cr:.15,d:"Thé bédouin face au désert.",meal:"breakfast"},
  {id:"dar_mat",n:"Dar Troglodyte",r:"sud_est",sub:"Matmata",cat:"restaurant",lt:33.54,lg:9.98,rt:4.2,dur:65,cost:20,hid:false,sn:["automne","hiver","printemps"],cr:.20,d:"Repas berbère dans maison souterraine.",meal:"lunch"},
  // DJERBA +
  {id:"borj_dj",n:"Borj El Kebir Djerba",r:"djerba",sub:"Houmt Souk",cat:"attraction",lt:33.88,lg:10.85,rt:4.1,dur:35,cost:5,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Fort espagnol XVe, tour des crânes.",meal:null},
  {id:"flamant",n:"Plage des Flamants",r:"djerba",sub:"Midoun",cat:"beach",lt:33.82,lg:11.00,rt:4.6,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.20,d:"Flamants roses, lagune turquoise.",meal:null},
  {id:"musee_dj",n:"Musée Guellala",r:"djerba",sub:"Erriadh",cat:"attraction",lt:33.75,lg:10.85,rt:4.0,dur:45,cost:7,hid:true,sn:["printemps","ete","automne","hiver"],cr:.15,d:"Traditions djerbiennes, poterie millénaire.",meal:null},
  {id:"crocodile",n:"Ferme Crocodiles",r:"djerba",sub:"Midoun",cat:"nature",lt:33.80,lg:10.93,rt:4.1,dur:50,cost:15,hid:false,sn:["printemps","ete","automne","hiver"],cr:.40,d:"400 crocodiles du Nil, jardin tropical.",meal:null},
  {id:"cafe_erriadh",n:"Café Fatma",r:"djerba",sub:"Erriadh",cat:"cafe",lt:33.82,lg:10.86,rt:4.2,dur:35,cost:8,hid:true,sn:["printemps","ete","automne","hiver"],cr:.10,d:"Café au milieu des fresques, homemade.",meal:"breakfast"},
  // SFAX +
  {id:"sfax_dar",n:"Dar Jellouli",r:"sfax",sub:"Sfax Ville",cat:"attraction",lt:34.74,lg:10.76,rt:4.1,dur:40,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.15,d:"Musée arts et traditions dans palais XVIIe.",meal:null},
  {id:"sfax_bab",n:"Bab Diwan",r:"sfax",sub:"Sfax Ville",cat:"attraction",lt:34.74,lg:10.76,rt:4.0,dur:20,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Porte monumentale, entrée médina.",meal:null},
  {id:"cafe_sfax",n:"Café El Diwan",r:"sfax",sub:"Sfax Ville",cat:"cafe",lt:34.74,lg:10.76,rt:4.0,dur:30,cost:6,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Face aux remparts, ambiance locale.",meal:"breakfast"},
  {id:"resto_sfax",n:"Chez Abid",r:"sfax",sub:"Sfax Ville",cat:"restaurant",lt:34.74,lg:10.77,rt:4.3,dur:65,cost:20,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Meilleur poisson grillé de Sfax.",meal:"lunch"},
  // === MORE EXPANDED DESTINATIONS V10 ===
  // TUNIS ++
  {id:"souk_att",n:"Souk El Attarine",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.17,rt:4.3,dur:40,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.55,d:"Souk des parfumeurs, essences et épices rares.",meal:null},
  {id:"tourbet",n:"Tourbet El Bey",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.17,rt:4.2,dur:35,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.12,d:"Mausolée royal husseinite, marbre et faïences.",meal:null},
  {id:"dar_bach",n:"Dar Bach Hamba",r:"tunis",sub:"Tunis Centre",cat:"attraction",lt:36.80,lg:10.17,rt:4.1,dur:30,cost:3,hid:true,sn:["printemps","ete","automne","hiver"],cr:.08,d:"Palais historique, expositions temporaires.",meal:null},
  {id:"resto_marsa",n:"Le Golfe La Marsa",r:"tunis",sub:"La Marsa & Gammarth",cat:"restaurant",lt:36.88,lg:10.33,rt:4.4,dur:70,cost:45,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Terrasse mer, fruits de mer premium.",meal:"dinner"},
  // SAHEL ++
  {id:"musee_sousse2",n:"Musée Dar Essid",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.83,lg:10.63,rt:4.3,dur:40,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.12,d:"Maison X siècle, mobilier ancien, vue médina.",meal:null},
  {id:"souk_jem",n:"Souk El Jem",r:"centre",sub:"El Jem",cat:"attraction",lt:35.30,lg:10.71,rt:4.0,dur:30,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.35,d:"Olives, tapis, artisanat berbère.",meal:null},
  {id:"cafe_eljem",n:"Café du Colisée",r:"centre",sub:"El Jem",cat:"cafe",lt:35.30,lg:10.71,rt:4.1,dur:30,cost:6,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Vue directe amphithéâtre, jus frais.",meal:"breakfast"},
  {id:"resto_monastir",n:"Le Pirate Monastir",r:"sahel",sub:"Monastir",cat:"restaurant",lt:35.78,lg:10.83,rt:4.2,dur:65,cost:28,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Poisson grillé, terrasse port.",meal:"dinner"},
  {id:"monastir_corniche",n:"Corniche Monastir",r:"sahel",sub:"Monastir",cat:"nature",lt:35.77,lg:10.83,rt:4.0,dur:40,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.40,d:"Promenade littorale, falaise et mer.",meal:null},
  // CAP BON ++
  {id:"pl_hammamet",n:"Plage Hammamet",r:"cap_bon",sub:"Hammamet",cat:"beach",lt:36.40,lg:10.62,rt:4.3,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.60,d:"Sable doré, eaux calmes, animée.",meal:null},
  {id:"medina_ham",n:"Médina Hammamet",r:"cap_bon",sub:"Hammamet",cat:"attraction",lt:36.40,lg:10.61,rt:4.2,dur:50,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.55,d:"Remparts face mer, ruelles fleuries.",meal:null},
  {id:"george_seb",n:"Villa George Sebastian",r:"cap_bon",sub:"Hammamet",cat:"attraction",lt:36.39,lg:10.62,rt:4.1,dur:40,cost:5,hid:true,sn:["printemps","ete","automne"],cr:.15,d:"Villa Art Déco 1920, jardins exotiques.",meal:null},
  {id:"resto_ham",n:"La Bella Marina",r:"cap_bon",sub:"Hammamet",cat:"restaurant",lt:36.40,lg:10.61,rt:4.3,dur:65,cost:35,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Pasta fruits de mer, vue Yasmine.",meal:"lunch"},
  {id:"cafe_ham",n:"Café Sidi Bouhdid",r:"cap_bon",sub:"Hammamet",cat:"cafe",lt:36.40,lg:10.61,rt:4.2,dur:35,cost:8,hid:false,sn:["printemps","ete","automne","hiver"],cr:.40,d:"Terrasse médina, vue golfe, thé menthe.",meal:"breakfast"},
  {id:"pl_nabeul",n:"Plage Nabeul",r:"cap_bon",sub:"Nabeul",cat:"beach",lt:36.45,lg:10.75,rt:4.0,dur:90,cost:0,hid:false,sn:["ete","printemps"],cr:.35,d:"Plage familiale calme, peu touristique.",meal:null},
  // NORD-OUEST ++
  {id:"aig_tab",n:"Aiguilles Tabarka",r:"nord_ouest",sub:"Tabarka",cat:"nature",lt:36.96,lg:8.76,rt:4.4,dur:40,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.20,d:"Formations rocheuses spectaculaires en mer.",meal:null},
  {id:"cafe_tab",n:"Café du Port Tabarka",r:"nord_ouest",sub:"Tabarka",cat:"cafe",lt:36.95,lg:8.76,rt:4.0,dur:30,cost:7,hid:false,sn:["printemps","ete","automne"],cr:.15,d:"Café face au fort, croissants frais.",meal:"breakfast"},
  {id:"resto_ain",n:"Chez Saïd",r:"nord_ouest",sub:"Aïn Draham",cat:"restaurant",lt:36.78,lg:8.68,rt:4.1,dur:60,cost:22,hid:true,sn:["printemps","ete","automne","hiver"],cr:.08,d:"Sanglier braisé, cuisine de montagne.",meal:"dinner"},
  // NORD-EST ++
  {id:"lac_biz",n:"Lac de Bizerte",r:"nord_est",sub:"Bizerte",cat:"nature",lt:37.24,lg:9.86,rt:4.0,dur:45,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.20,d:"Promenade lac, pont mobile, pêcheurs.",meal:null},
  {id:"medina_biz",n:"Médina Bizerte",r:"nord_est",sub:"Bizerte",cat:"attraction",lt:37.27,lg:9.87,rt:4.1,dur:50,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Ruelles andalouses, mosquées, zaouïas.",meal:null},
  // KAIROUAN ++
  {id:"k_tapis",n:"Atelier Tapis Kairouan",r:"centre",sub:"Kairouan",cat:"attraction",lt:35.68,lg:10.10,rt:4.2,dur:45,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Démonstration tissage, noeuds persans.",meal:null},
  {id:"k_makroudh",n:"Pâtisserie El Amir",r:"centre",sub:"Kairouan",cat:"cafe",lt:35.68,lg:10.10,rt:4.3,dur:25,cost:4,hid:false,sn:["printemps","ete","automne","hiver"],cr:.50,d:"Meilleur makroudh de Tunisie.",meal:"breakfast"},
  {id:"k_resto",n:"Dar El Bey Kairouan",r:"centre",sub:"Kairouan",cat:"restaurant",lt:35.68,lg:10.10,rt:4.2,dur:65,cost:25,hid:true,sn:["printemps","ete","automne","hiver"],cr:.15,d:"Riad restauré, tagine agneau aux pruneaux.",meal:"dinner"},
  // SUD-OUEST ++
  {id:"medina_toz",n:"Médina Tozeur",r:"sud_ouest",sub:"Tozeur",cat:"attraction",lt:33.92,lg:8.13,rt:4.3,dur:50,cost:0,hid:false,sn:["automne","hiver","printemps"],cr:.20,d:"Briques Ouled Hadef, architecture unique.",meal:null},
  {id:"musee_dar",n:"Musée Dar Charaït",r:"sud_ouest",sub:"Tozeur",cat:"attraction",lt:33.92,lg:8.12,rt:4.1,dur:40,cost:7,hid:false,sn:["automne","hiver","printemps"],cr:.12,d:"Traditions oasiennes, costumes anciens.",meal:null},
  {id:"nefta_mosque",n:"Mosquée Nefta",r:"sud_ouest",sub:"Nefta & Chebika",cat:"mosque",lt:33.87,lg:7.88,rt:4.0,dur:25,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.05,d:"Coupoles blanches au-dessus de la corbeille.",meal:null},
  // SUD-EST ++
  {id:"douz_souk",n:"Souk de Douz",r:"sud_ouest",sub:"Douz",cat:"attraction",lt:33.46,lg:8.83,rt:4.0,dur:40,cost:0,hid:false,sn:["automne","hiver"],cr:.20,d:"Marché du jeudi, dattes, artisanat nomade.",meal:null},
  {id:"ksar_ghilane",n:"Ksar Ghilane",r:"sud_ouest",sub:"Douz",cat:"nature",lt:33.49,lg:8.44,rt:4.5,dur:180,cost:50,hid:true,sn:["automne","hiver"],cr:.05,d:"Oasis saharienne, sources chaudes, bivouac.",meal:null},
  {id:"resto_tat",n:"Dar Tataouine",r:"sud_est",sub:"Tataouine",cat:"restaurant",lt:32.93,lg:10.45,rt:4.1,dur:60,cost:18,hid:true,sn:["automne","hiver","printemps"],cr:.05,d:"Cuisine berbère, brik dannouni.",meal:"lunch"},
  // DJERBA ++
  {id:"phare_dj",n:"Phare Taguermess",r:"djerba",sub:"Midoun",cat:"attraction",lt:33.84,lg:11.01,rt:4.0,dur:30,cost:0,hid:true,sn:["printemps","ete","automne","hiver"],cr:.10,d:"Plus ancien phare de Tunisie, panorama 360°.",meal:null},
  {id:"lella_hadj",n:"Plage Lella Hadhria",r:"djerba",sub:"Midoun",cat:"beach",lt:33.80,lg:10.98,rt:4.3,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.30,d:"Longue plage de sable blanc, clubs.",meal:null},
  {id:"ajim",n:"Port Ajim",r:"djerba",sub:"Houmt Souk",cat:"attraction",lt:33.73,lg:10.75,rt:3.9,dur:35,cost:0,hid:true,sn:["printemps","ete","automne","hiver"],cr:.08,d:"Port cantina Star Wars, pêche éponge.",meal:null},
  {id:"dar_dj2",n:"Restaurant Haroun",r:"djerba",sub:"Houmt Souk",cat:"restaurant",lt:33.88,lg:10.86,rt:4.3,dur:65,cost:28,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"Terrasse fondouk, couscous au poulpe.",meal:"dinner"},
  // SFAX ++
  {id:"sfax_olives",n:"Musée de l'Olive Sfax",r:"sfax",sub:"Sfax Ville",cat:"attraction",lt:34.74,lg:10.75,rt:3.9,dur:35,cost:3,hid:true,sn:["printemps","automne","hiver"],cr:.08,d:"Histoire oléicole, pressoirs anciens.",meal:null},
  {id:"kerk_pl",n:"Plage Kerkennah",r:"sfax",sub:"Kerkennah",cat:"beach",lt:34.70,lg:11.18,rt:4.1,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.08,d:"Plage préservée, charfia pêche ancestrale.",meal:null},
  {id:"resto_kerk",n:"Le Pêcheur Kerkennah",r:"sfax",sub:"Kerkennah",cat:"restaurant",lt:34.70,lg:11.17,rt:4.2,dur:60,cost:18,hid:true,sn:["printemps","ete","automne"],cr:.05,d:"Poisson du jour, octopus grillé.",meal:"lunch"},
  // BEACH CLUBS
  {id:"ghar",n:"Ghar Melh Beach",r:"nord_est",sub:"Bizerte",cat:"beach",lt:37.17,lg:10.19,rt:4.4,dur:120,cost:15,hid:false,sn:["ete"],cr:.35,d:"Plage sauvage, lagune préservée.",meal:null},
  {id:"rafraf",n:"Rafraf Beach",r:"nord_est",sub:"Bizerte",cat:"beach",lt:37.19,lg:10.18,rt:4.5,dur:120,cost:0,hid:false,sn:["ete"],cr:.40,d:"Plus belle plage du Nord, eaux cristallines.",meal:null},
  {id:"capang",n:"Cap Angela",r:"nord_est",sub:"Bizerte",cat:"beach",lt:37.34,lg:9.75,rt:4.3,dur:90,cost:0,hid:true,sn:["ete","printemps"],cr:.08,d:"Point le plus au Nord d'Afrique.",meal:null},
  {id:"coco",n:"Coco Beach Bizerte",r:"nord_est",sub:"Bizerte",cat:"beach",lt:37.28,lg:9.88,rt:4.2,dur:120,cost:25,hid:false,sn:["ete"],cr:.50,d:"Beach club, ambiance festive.",meal:null},
  {id:"tabsus",n:"Tabsus Beach Club",r:"sahel",sub:"Mahdia",cat:"beach",lt:35.50,lg:11.06,rt:4.3,dur:120,cost:20,hid:false,sn:["ete"],cr:.30,d:"Beach club branché face mer.",meal:null},
  {id:"hamra",n:"El Hamra Beach",r:"sahel",sub:"Mahdia",cat:"beach",lt:35.52,lg:11.04,rt:4.1,dur:100,cost:10,hid:true,sn:["ete"],cr:.20,d:"Plage dorée, ambiance locale.",meal:null},
  {id:"pparis",n:"Petit Paris",r:"cap_bon",sub:"Kélibia",cat:"beach",lt:36.85,lg:11.10,rt:4.4,dur:120,cost:20,hid:false,sn:["ete"],cr:.35,d:"Beach club chic, DJ sets.",meal:null},
  {id:"mansoura",n:"Mansoura Beach",r:"cap_bon",sub:"Kélibia",cat:"beach",lt:36.83,lg:11.08,rt:4.5,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.25,d:"Eau turquoise, falaises impressionnantes.",meal:null},
  {id:"elbelge",n:"El Belge Beach",r:"cap_bon",sub:"Kélibia",cat:"beach",lt:36.84,lg:11.09,rt:4.2,dur:100,cost:10,hid:true,sn:["ete"],cr:.15,d:"Crique secrète, snorkeling.",meal:null},
  // 5-STAR HOTELS
  {id:"h_cigale",n:"La Cigale Tabarka",r:"nord_ouest",sub:"Tabarka",cat:"hotel",lt:36.96,lg:8.74,rt:4.7,dur:0,cost:350,hid:false,sn:["printemps","ete","automne","hiver"],cr:.20,d:"5★ Resort & spa, golf, plage privée.",meal:null},
  {id:"h_marriott",n:"Tunis Marriott",r:"tunis",sub:"La Marsa & Gammarth",cat:"hotel",lt:36.90,lg:10.30,rt:4.6,dur:0,cost:380,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"5★ Vue mer Gammarth, spa, piscine.",meal:null},
  {id:"h_four",n:"Four Seasons Tunis",r:"tunis",sub:"La Marsa & Gammarth",cat:"hotel",lt:36.91,lg:10.29,rt:4.9,dur:0,cost:650,hid:false,sn:["printemps","ete","automne","hiver"],cr:.15,d:"5★ Luxe absolu, plage privée, 3 restaurants.",meal:null},
  {id:"h_radisson",n:"Radisson Blu Hammamet",r:"cap_bon",sub:"Hammamet",cat:"hotel",lt:36.40,lg:10.60,rt:4.4,dur:0,cost:280,hid:false,sn:["printemps","ete","automne","hiver"],cr:.30,d:"5★ Face mer, thalasso, all inclusive.",meal:null},
  {id:"h_regency",n:"Regency Tunis",r:"tunis",sub:"La Marsa & Gammarth",cat:"hotel",lt:36.89,lg:10.30,rt:4.5,dur:0,cost:300,hid:false,sn:["printemps","ete","automne","hiver"],cr:.20,d:"5★ Gammarth, piscine panoramique.",meal:null},
  {id:"h_moven",n:"Mövenpick Sousse",r:"sahel",sub:"Sousse",cat:"hotel",lt:35.84,lg:10.58,rt:4.5,dur:0,cost:320,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"5★ Resort, spa, parc aquatique.",meal:null},
  {id:"h_anant",n:"Anantara Tozeur",r:"sud_ouest",sub:"Tozeur",cat:"hotel",lt:33.93,lg:8.12,rt:4.8,dur:0,cost:500,hid:false,sn:["automne","hiver","printemps"],cr:.10,d:"5★ Luxe oasis, vue palmeraie et désert.",meal:null},
  {id:"h_mouradi",n:"Mouradi Djerba",r:"djerba",sub:"Midoun",cat:"hotel",lt:33.79,lg:10.95,rt:4.3,dur:0,cost:250,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"5★ Plage privée, all inclusive.",meal:null},
  {id:"h_royal",n:"Royal Tulip Hammamet",r:"cap_bon",sub:"Hammamet",cat:"hotel",lt:36.41,lg:10.59,rt:4.4,dur:0,cost:260,hid:false,sn:["printemps","ete","automne","hiver"],cr:.20,d:"5★ Yasmine, thalasso, 4 piscines.",meal:null},

  // MORE SAHEL
  {id:"s_kantaoui_m",n:"Marina Kantaoui",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.89,lg:10.60,rt:4.2,dur:60,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.55,d:"Marina luxe, bateaux, shopping bord de mer.",meal:null},
  {id:"s_remada",n:"Remada Palace",r:"sahel",sub:"Sousse",cat:"restaurant",lt:35.84,lg:10.63,rt:4.3,dur:70,cost:30,hid:false,sn:["printemps","ete","automne","hiver"],cr:.35,d:"Gastronomie tuniso-italienne, terrasse mer.",meal:"dinner"},
  {id:"s_mahdiafort",n:"Fort Mahdia",r:"sahel",sub:"Mahdia",cat:"attraction",lt:35.51,lg:11.07,rt:4.2,dur:40,cost:3,hid:false,sn:["printemps","automne","hiver"],cr:.20,d:"Phare et fortifications face Méditerranée.",meal:null},
  {id:"s_eljem_mus",n:"Musée El Jem",r:"centre",sub:"El Jem",cat:"attraction",lt:35.30,lg:10.71,rt:4.3,dur:40,cost:8,hid:true,sn:["printemps","automne","hiver"],cr:.30,d:"Mosaïques uniques, villas romaines.",meal:null},
  // MORE TUNIS
  {id:"t_tophet",n:"Tophet Carthage",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.84,lg:10.32,rt:4.1,dur:35,cost:5,hid:true,sn:["printemps","automne","hiver"],cr:.25,d:"Sanctuaire punique, stèles votives.",meal:null},
  {id:"t_palais",n:"Palais Ennejma Ezzahra",r:"tunis",sub:"Carthage & Sidi Bou Saïd",cat:"attraction",lt:36.87,lg:10.34,rt:4.4,dur:50,cost:5,hid:true,sn:["printemps","ete","automne","hiver"],cr:.20,d:"Palais baron d'Erlanger, musique arabe.",meal:null},
  {id:"t_medina_r",n:"Resto Dar Slah",r:"tunis",sub:"Tunis Centre",cat:"restaurant",lt:36.80,lg:10.17,rt:4.3,dur:70,cost:28,hid:true,sn:["printemps","ete","automne","hiver"],cr:.15,d:"Kamounia, tajine, cuisine tunisoise authentique.",meal:"lunch"},
  {id:"t_tgm",n:"Balade TGM Banlieue",r:"tunis",sub:"La Marsa & Gammarth",cat:"nature",lt:36.88,lg:10.31,rt:4.0,dur:40,cost:1,hid:true,sn:["printemps","ete","automne"],cr:.20,d:"Train pittoresque longeant la mer.",meal:null},
  // MORE CAP BON
  {id:"cb_dar_chic",n:"Dar Chichone",r:"cap_bon",sub:"Nabeul",cat:"restaurant",lt:36.45,lg:10.73,rt:4.4,dur:70,cost:35,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"Gastronomie capbonnaise, brick tunisien.",meal:"dinner"},
  {id:"cb_plage_h",n:"Plage Hammamet",r:"cap_bon",sub:"Hammamet",cat:"beach",lt:36.40,lg:10.62,rt:4.3,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.60,d:"Plage mythique de sable doré.",meal:null},
  {id:"cb_medina_h",n:"Médina Hammamet",r:"cap_bon",sub:"Hammamet",cat:"attraction",lt:36.40,lg:10.61,rt:4.2,dur:50,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.55,d:"Petite médina fortifiée face mer.",meal:null},
  {id:"cb_neapolis",n:"Neapolis Nabeul",r:"cap_bon",sub:"Nabeul",cat:"attraction",lt:36.46,lg:10.73,rt:4.0,dur:40,cost:5,hid:true,sn:["printemps","automne"],cr:.08,d:"Site archéo romain, garum et mosaïques.",meal:null},
  // MORE NORD-EST
  {id:"ne_lac_biz",n:"Lac de Bizerte",r:"nord_est",sub:"Bizerte",cat:"nature",lt:37.22,lg:9.85,rt:4.0,dur:50,cost:0,hid:false,sn:["printemps","ete","automne"],cr:.15,d:"Plus grand lac naturel, flamants.",meal:null},
  {id:"ne_plage_r",n:"Plage Rémel",r:"nord_est",sub:"Bizerte",cat:"beach",lt:37.21,lg:10.15,rt:4.3,dur:100,cost:0,hid:true,sn:["ete"],cr:.12,d:"Plage sauvage au sable blanc doré.",meal:null},
  // MORE SUD
  {id:"se_ghomra",n:"Ghomrassen",r:"sud_est",sub:"Tataouine",cat:"attraction",lt:33.06,lg:10.34,rt:4.0,dur:40,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.03,d:"Village berbère, ksour en ruines.",meal:null},
  {id:"se_resto_d",n:"Café Désert",r:"sud_ouest",sub:"Douz",cat:"restaurant",lt:33.46,lg:8.82,rt:4.1,dur:60,cost:18,hid:false,sn:["automne","hiver"],cr:.15,d:"Agneau méchoui, sous tente bédouine.",meal:"dinner"},
  {id:"sw_vieuxtozeur",n:"Vieux Tozeur Ouled Hadef",r:"sud_ouest",sub:"Tozeur",cat:"attraction",lt:33.92,lg:8.14,rt:4.3,dur:50,cost:0,hid:false,sn:["automne","hiver","printemps"],cr:.20,d:"Briques jaunes géométriques, ruelles.",meal:null},
  {id:"sw_lezard",n:"Lézard Rouge Train",r:"sud_ouest",sub:"Tamerza",cat:"attraction",lt:34.35,lg:7.93,rt:4.4,dur:90,cost:15,hid:false,sn:["automne","hiver","printemps"],cr:.15,d:"Train historique gorges de Selja.",meal:null},
  // MORE DJERBA
  {id:"dj_plsidi",n:"Plage Sidi Mahrez",r:"djerba",sub:"Midoun",cat:"beach",lt:33.83,lg:10.98,rt:4.5,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.40,d:"Plus belle plage de Djerba, sable blanc.",meal:null},
  {id:"dj_lella",n:"Lella Hadhria Museum",r:"djerba",sub:"Midoun",cat:"attraction",lt:33.80,lg:10.93,rt:4.2,dur:50,cost:12,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"1000 pièces art tunisien et arabe.",meal:null},
  {id:"dj_cafe_har",n:"Café Haroun",r:"djerba",sub:"Houmt Souk",cat:"cafe",lt:33.87,lg:10.85,rt:4.3,dur:35,cost:7,hid:true,sn:["printemps","ete","automne","hiver"],cr:.20,d:"Vue port pêcheurs, café turc parfait.",meal:"breakfast"},
  // MORE KAIROUAN
  {id:"k_zaouia",n:"Zaouia Sidi Abid",r:"centre",sub:"Kairouan",cat:"mosque",lt:35.68,lg:10.10,rt:4.2,dur:25,cost:0,hid:true,sn:["printemps","automne","hiver"],cr:.15,d:"Zellige andalou, coupoles blanches.",meal:null},
  {id:"k_makroudh2",n:"Pâtisserie Makroudh",r:"centre",sub:"Kairouan",cat:"restaurant",lt:35.68,lg:10.10,rt:4.3,dur:30,cost:5,hid:false,sn:["printemps","ete","automne","hiver"],cr:.40,d:"Meilleur makroudh de Tunisie, dattes Deglet.",meal:"breakfast"},
  {id:"h_bizerta",n:"Bizerta Resort",r:"nord_est",sub:"Bizerte",cat:"hotel",lt:37.27,lg:9.88,rt:4.3,dur:0,cost:220,hid:false,sn:["printemps","ete","automne","hiver"],cr:.20,d:"4★ Face vieux port, piscine, spa.",meal:null},
  {id:"h_capbon",n:"Hasdrubal Hammamet",r:"cap_bon",sub:"Hammamet",cat:"hotel",lt:36.40,lg:10.62,rt:4.6,dur:0,cost:400,hid:false,sn:["printemps","ete","automne","hiver"],cr:.20,d:"5★ Thalasso & Spa, plage privée, 5 restos.",meal:null},
  {id:"h_cigale_m",n:"La Cigale Monastir",r:"sahel",sub:"Monastir",cat:"hotel",lt:35.77,lg:10.82,rt:4.5,dur:0,cost:300,hid:false,sn:["printemps","ete","automne","hiver"],cr:.25,d:"5★ Front de mer, golf, spa.",meal:null},
  // === ZAGHOUAN ===
  {id:"z_temple",n:"Temple des Eaux",r:"zaghouan",sub:"Zaghouan",cat:"attraction",lt:36.40,lg:10.14,rt:4.4,dur:50,cost:5,hid:false,sn:["printemps","automne","hiver"],cr:.15,d:"Temple romain dédié aux nymphes, aqueduc.",meal:null},
  {id:"z_jbel",n:"Jbel Zaghouan",r:"zaghouan",sub:"Zaghouan",cat:"nature",lt:36.38,lg:10.12,rt:4.3,dur:120,cost:0,hid:true,sn:["printemps","automne"],cr:.08,d:"Randonnée 1295m, panorama sur le Cap Bon.",meal:null},
  {id:"z_medina",n:"Médina Zaghouan",r:"zaghouan",sub:"Zaghouan",cat:"attraction",lt:36.40,lg:10.14,rt:4.0,dur:40,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.15,d:"Ruelles blanches, artisanat, calme.",meal:null},
  {id:"z_thermes",n:"Thermes Jbel Oust",r:"zaghouan",sub:"Jbel Oust",cat:"nature",lt:36.46,lg:10.04,rt:4.1,dur:60,cost:15,hid:false,sn:["printemps","automne","hiver"],cr:.10,d:"Sources chaudes naturelles, spa ancestral.",meal:null},
  {id:"z_kayak",n:"Kayak Barrage Zaghouan",r:"zaghouan",sub:"Zaghouan",cat:"activity",lt:36.38,lg:10.10,rt:4.2,dur:90,cost:35,hid:false,sn:["printemps","ete","automne"],cr:.10,d:"Kayak sur lac de barrage, cadre montagneux.",meal:null},
  {id:"z_cafe",n:"Café Ain El Jenna",r:"zaghouan",sub:"Zaghouan",cat:"cafe",lt:36.40,lg:10.14,rt:4.1,dur:30,cost:6,hid:false,sn:["printemps","ete","automne","hiver"],cr:.10,d:"Source fraîche, thé sous les arbres.",meal:"breakfast"},
  {id:"z_resto",n:"Le Zaghouanais",r:"zaghouan",sub:"Zaghouan",cat:"restaurant",lt:36.40,lg:10.14,rt:4.0,dur:60,cost:20,hid:false,sn:["printemps","ete","automne","hiver"],cr:.10,d:"Cuisine montagnarde, agneau rôti.",meal:"lunch"},
  // === NORD-OUEST EXPANDED: Béja, Makthar, Bou Salem ===
  {id:"nw_beja",n:"Béja Ville",r:"nord_ouest",sub:"Béja",cat:"attraction",lt:36.73,lg:9.18,rt:3.9,dur:50,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.05,d:"Grenier de Rome, architecture coloniale.",meal:null},
  {id:"nw_thibar",n:"Domaine Thibar",r:"nord_ouest",sub:"Béja",cat:"nature",lt:36.52,lg:9.10,rt:4.0,dur:60,cost:10,hid:true,sn:["printemps","automne"],cr:.03,d:"Vignobles coloniaux, dégustation vin tunisien.",meal:null},
  {id:"nw_makthar",n:"Ruines Makthar",r:"nord_ouest",sub:"Béja",cat:"attraction",lt:35.85,lg:9.20,rt:4.2,dur:70,cost:5,hid:true,sn:["printemps","automne"],cr:.03,d:"Arc Trajan, thermes romains, forum antique.",meal:null},
  // === ACTIVITÉS TOURISTIQUES ===
  // Tozeur
  {id:"toz_quad",n:"Quad Désert Tozeur",r:"sud_ouest",sub:"Tozeur",cat:"activity",lt:33.90,lg:8.10,rt:4.5,dur:120,cost:80,hid:false,sn:["automne","hiver","printemps"],cr:.25,d:"Excursion quad dans les dunes, Chott el-Jérid.",meal:null},
  {id:"toz_chameau",n:"Balade Chameau Douz",r:"sud_ouest",sub:"Douz",cat:"activity",lt:33.46,lg:8.82,rt:4.4,dur:90,cost:40,hid:false,sn:["automne","hiver"],cr:.30,d:"Méharée au coucher du soleil dans le Grand Erg.",meal:null},
  {id:"toz_bivouac",n:"Bivouac Sahara",r:"sud_ouest",sub:"Douz",cat:"activity",lt:33.40,lg:8.80,rt:4.6,dur:180,cost:120,hid:true,sn:["automne","hiver"],cr:.05,d:"Nuit sous les étoiles, repas bédouin, feu de camp.",meal:null},
  // Mahdia
  {id:"mah_paddle",n:"Paddle Mahdia",r:"sahel",sub:"Mahdia",cat:"activity",lt:35.50,lg:11.06,rt:4.2,dur:60,cost:30,hid:false,sn:["ete","printemps"],cr:.20,d:"Stand-up paddle, eau cristalline face cap Afrique.",meal:null},
  // Monastir
  {id:"mon_plongee",n:"Plongée Monastir",r:"sahel",sub:"Monastir",cat:"activity",lt:35.78,lg:10.85,rt:4.3,dur:120,cost:80,hid:false,sn:["ete","printemps"],cr:.15,d:"Plongée épave, récifs, poissons méditerranéens.",meal:null},
  // El Haouaria
  {id:"hao_plongee",n:"Plongée El Haouaria",r:"cap_bon",sub:"El Haouaria",cat:"activity",lt:37.06,lg:11.00,rt:4.5,dur:120,cost:80,hid:false,sn:["ete","printemps"],cr:.10,d:"Meilleur spot plongée Tunisie, grottes sous-marines.",meal:null},
  {id:"hao_bateau",n:"Excursion Zembra",r:"cap_bon",sub:"El Haouaria",cat:"activity",lt:37.06,lg:11.00,rt:4.6,dur:180,cost:100,hid:false,sn:["ete"],cr:.08,d:"Bateau vers îles Zembra & Zembretta, réserve naturelle.",meal:null},
  // Djerba
  {id:"dj_parachute",n:"Parachute Djerba",r:"djerba",sub:"Midoun",cat:"activity",lt:33.82,lg:10.98,rt:4.3,dur:30,cost:60,hid:false,sn:["ete","printemps"],cr:.25,d:"Parachute ascensionnel, vue île depuis les airs.",meal:null},
  {id:"dj_cheval",n:"Balade Cheval Djerba",r:"djerba",sub:"Midoun",cat:"activity",lt:33.80,lg:10.95,rt:4.1,dur:60,cost:35,hid:false,sn:["printemps","ete","automne","hiver"],cr:.15,d:"Galop sur plage, coucher de soleil.",meal:null},
  // Sousse
  {id:"s_bled_arbi",n:"Bled Arbi Sousse",r:"sahel",sub:"Sousse",cat:"attraction",lt:35.82,lg:10.59,rt:4.0,dur:60,cost:0,hid:false,sn:["printemps","ete","automne","hiver"],cr:.20,d:"Quartier traditionnel, vie locale authentique.",meal:null},
  // Tabarka
  {id:"tab_plongee",n:"Plongée Tabarka",r:"nord_ouest",sub:"Tabarka",cat:"activity",lt:36.96,lg:8.75,rt:4.4,dur:120,cost:80,hid:false,sn:["ete","printemps"],cr:.15,d:"Corail rouge, mérous, fonds spectaculaires.",meal:null},
  // Bizerte
  {id:"biz_bateau",n:"Tour Bateau Bizerte",r:"nord_est",sub:"Bizerte",cat:"activity",lt:37.28,lg:9.87,rt:4.2,dur:90,cost:45,hid:false,sn:["ete","printemps"],cr:.20,d:"Tour du vieux port et lac, grottes côtières.",meal:null},
  // Hammamet
  {id:"ham_parachute",n:"Parachute Hammamet",r:"cap_bon",sub:"Hammamet",cat:"activity",lt:36.40,lg:10.62,rt:4.1,dur:30,cost:50,hid:false,sn:["ete","printemps"],cr:.30,d:"Vol en parachute ascensionnel sur le golfe.",meal:null},
  // === SUD-EST EXPANDED: Gabès, Médenine, Zarzis ===
  {id:"se_gabes",n:"Oasis Gabès",r:"sud_est",sub:"Gabès",cat:"nature",lt:33.88,lg:10.10,rt:4.1,dur:70,cost:0,hid:false,sn:["automne","hiver","printemps"],cr:.10,d:"Unique oasis maritime au monde, palmeraie littorale.",meal:null},
  {id:"se_gabes_souk",n:"Souk Jara Gabès",r:"sud_est",sub:"Gabès",cat:"attraction",lt:33.88,lg:10.10,rt:4.0,dur:40,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.10,d:"Grand marché traditionnel, henné, épices.",meal:null},
  {id:"se_medenine",n:"Ksour Médenine",r:"sud_est",sub:"Médenine & Zarzis",cat:"attraction",lt:33.35,lg:10.50,rt:4.2,dur:50,cost:3,hid:false,sn:["automne","hiver","printemps"],cr:.08,d:"Greniers voûtés berbères, architecture spectaculaire.",meal:null},
  {id:"se_zarzis",n:"Plage Zarzis",r:"sud_est",sub:"Médenine & Zarzis",cat:"beach",lt:33.50,lg:11.10,rt:4.3,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.10,d:"Sable blanc immaculé, mer turquoise, calme.",meal:null},
  {id:"se_douiret",n:"Village Douiret",r:"sud_est",sub:"Tataouine",cat:"attraction",lt:32.87,lg:10.27,rt:4.4,dur:60,cost:0,hid:true,sn:["automne","hiver","printemps"],cr:.03,d:"Village troglodyte abandonné, vue époustouflante.",meal:null},
  {id:"se_cafe_gab",n:"Café Oasis Gabès",r:"sud_est",sub:"Gabès",cat:"cafe",lt:33.88,lg:10.10,rt:4.0,dur:30,cost:5,hid:false,sn:["printemps","ete","automne","hiver"],cr:.08,d:"Thé sous palmiers, frais de dattes.",meal:"breakfast"},
  {id:"se_resto_gab",n:"Le Palmier Gabès",r:"sud_est",sub:"Gabès",cat:"restaurant",lt:33.88,lg:10.10,rt:4.1,dur:60,cost:18,hid:false,sn:["printemps","ete","automne","hiver"],cr:.08,d:"Poisson charmoula, spécialité gabésienne.",meal:"lunch"},

  // === MISSING NORD-OUEST: Bou Salem, Tajerouine ===
  {id:"nw_bousalem",n:"Bou Salem",r:"nord_ouest",sub:"Bou Salem",cat:"nature",lt:36.62,lg:8.97,rt:3.8,dur:40,cost:0,hid:true,sn:["printemps","automne"],cr:.03,d:"Vallée de la Medjerda, agriculture, calme rural.",meal:null},
  {id:"nw_tajerouine",n:"Tajerouine",r:"nord_ouest",sub:"Le Kef",cat:"attraction",lt:35.89,lg:8.55,rt:3.7,dur:40,cost:0,hid:true,sn:["printemps","automne"],cr:.02,d:"Petite ville historique, ruines romaines Haïdra à proximité.",meal:null},
  {id:"nw_haidra",n:"Ruines Haïdra",r:"nord_ouest",sub:"Le Kef",cat:"attraction",lt:35.57,lg:8.46,rt:4.3,dur:80,cost:5,hid:true,sn:["printemps","automne"],cr:.02,d:"Site archéologique majeur, arc de Septime Sévère, basiliques.",meal:null},
  // === MISSING NORD-EST: Ghar El Melh, Raf Raf plage ===
  {id:"ne_ghar",n:"Ghar El Melh",r:"nord_est",sub:"Ghar El Melh",cat:"attraction",lt:37.17,lg:10.19,rt:4.1,dur:50,cost:0,hid:true,sn:["printemps","ete","automne"],cr:.05,d:"Port punique, forts ottomans, lagune préservée.",meal:null},
  {id:"ne_rafraf",n:"Plage Raf Raf",r:"nord_est",sub:"Raf Raf",cat:"beach",lt:37.19,lg:10.18,rt:4.4,dur:100,cost:0,hid:false,sn:["ete","printemps"],cr:.15,d:"Plus belle plage du Nord, sable fin, falaises.",meal:null},
  {id:"ne_cafe_raf",n:"Café Sidi Ali El Mekki",r:"nord_est",sub:"Ghar El Melh",cat:"cafe",lt:37.18,lg:10.17,rt:4.0,dur:30,cost:5,hid:true,sn:["printemps","ete","automne"],cr:.05,d:"Vue lagune et montagne, thé aux pignons.",meal:"breakfast"},
  // === MISSING CAP BON: Korba, Soliman ===
  {id:"cb_korba",n:"Lagune de Korba",r:"cap_bon",sub:"Korba",cat:"nature",lt:36.58,lg:10.86,rt:4.2,dur:50,cost:0,hid:false,sn:["printemps","automne","hiver"],cr:.10,d:"Zone humide Ramsar, flamants roses, oiseaux migrateurs.",meal:null},
  {id:"cb_korba_pl",n:"Plage Korba",r:"cap_bon",sub:"Korba",cat:"beach",lt:36.58,lg:10.87,rt:4.0,dur:80,cost:0,hid:false,sn:["ete","printemps"],cr:.15,d:"Longue plage sauvage, peu fréquentée.",meal:null},
  {id:"cb_soliman",n:"Soliman Plage",r:"cap_bon",sub:"Soliman",cat:"beach",lt:36.70,lg:10.52,rt:3.9,dur:80,cost:0,hid:false,sn:["ete","printemps"],cr:.20,d:"Plage familiale proche Tunis, restaurants poisson.",meal:null},
  {id:"cb_soliman_v",n:"Marché Soliman",r:"cap_bon",sub:"Soliman",cat:"attraction",lt:36.69,lg:10.49,rt:3.8,dur:40,cost:0,hid:true,sn:["printemps","ete","automne","hiver"],cr:.10,d:"Souk dominical animé, produits du Cap Bon.",meal:null},

];
